# Generated by Django 3.2.7 on 2021-10-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fallacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(default='About project')),
                ('example1_text', models.TextField(default='Пример 1')),
                ('example1_image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('example2_text', models.TextField(default='Пример 2')),
                ('example2_image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('another_names', models.TextField(default='Another name 1')),
            ],
        ),
    ]
