# Generated by Django 3.2.8 on 2021-10-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0002_fallacy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fallacy',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
