# Generated by Django 3.2.8 on 2021-10-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0003_auto_20211021_1415'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='shop_main_app_category',
        ),
    ]
