# Generated by Django 3.2.8 on 2021-11-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211105_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flat',
            field=models.CharField(max_length=3, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house',
            field=models.CharField(max_length=255, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='order',
            name='village',
            field=models.CharField(max_length=255, verbose_name='Улица/Проспект/Переулок'),
        ),
    ]
