# Generated by Django 3.2.8 on 2021-11-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211106_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flat',
            field=models.IntegerField(verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house',
            field=models.IntegerField(verbose_name='Дом'),
        ),
    ]
