# Generated by Django 3.2.8 on 2021-11-12 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_category'),
        ('order', '0004_auto_20211112_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flat',
            field=models.CharField(max_length=255, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house',
            field=models.CharField(max_length=255, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.product'),
        ),
    ]
